[versions]
kotlin = "2.1.20"
ktor = "3.1.3"
mavenpublish = "0.32.0"

[libraries]
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenpublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenpublish" }
